smc_run: use env SMC_RUN_BPF to decide if using ebpf or not
Signed-off-by: D. Wythe <alibuda@linux.alibaba.com>

diff --git a/smc_run b/smc_run
--- a/smc_run
+++ b/smc_run
@@ -80,12 +80,13 @@ export SMC_DEBUG;
 # Execute the specified command.
 #
 
-smc_run.bpf -s load > /dev/null 2>&1
-if [ $? -eq 0 ]; then
-	smc_run.bpf "$@"
-	exit $?;
-else
-	echo "smc_run: Try load eBPF prog failed, run with AF_SMC via LD_PRELOAD."
+if [ -n "$SMC_RUN_BPF" ] && [ "$SMC_RUN_BPF" -ne 0 ]; then
+	smc_run.bpf -p $$ > /dev/null 2>&1
+	if [ $? -eq 0 ]; then
+		exec "$@"
+		exit $?;
+	fi
+	# failover to AF_SMC with LD_PRELOAD
 fi
 
 export LD_PRELOAD=$LD_PRELOAD:$LIB_NAME;
